platform :ios, '6.0'
pod 'AFNetworking', '~> 1.3.1'
pod 'TSMessages'
pod 'REMenu', '~> 1.3.5'
pod 'RestKit', '~> 0.20.3'
pod 'RFKeychain', '~> 0.1'
pod 'UIImage-Categories', '~> 0.0.1'
pod 'MBProgressHUD'
pod 'STTweetLabel', '~> 2.2.2'
pod 'Facebook-iOS-SDK', '~> 3.5'

# not used yet
# pod 'NSData+Base64'
# pod 'JMTabView'
# pod 'SDSegmentedControl'
# pod 'NUI'
# pod 'Foursquare-API-v2'
