platform :ios, '6.0'
pod 'Parse'
# pod 'Foursquare-API-v2'
pod 'AFNetworking', '~> 1.3.1'
pod 'MBProgressHUD'
pod 'TSMessages'
pod 'STTweetLabel'
pod 'REMenu', '~> 1.3.5'
pod 'NUI'
pod 'SDSegmentedControl'
pod 'JMTabView'

